apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend
spec:
  type: ClusterIP  #LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
